apiVersion: apps/v1
kind: Deployment
metadata:
  name: dptname
spec:
  replicas: 2
  selector:
    matchLabels:
      dt: dt1
  template:
    metadata:
      labels:
        dt: dt1
    spec:
      containers:
        - name: c3
          image: deepakgonsalves63/httpd3
          ports:
            - containerPort: 80
      nodeSelector:
        n: s
